name: APPerms
main: ap.apperms.apdevteam.APPerms
version: ${project.version}
api-version: 1.14
authors: [TylerS1066]
depend: [Vault]
commands:
   apgivedonor:
       description: Gives a player a donor rank
       usage: /<command> <player> <rank>
       permission: APPerm.givedonor
   apremovedonor:
       description: Removes a player's donor ranks
       usage: /<command> <player>
       permission: APPerm.removedonor
   fixranks:
       description: Fixes the permissions for a player by re-stacking their ranks
       usage: /<command> <player>
       permission: APPerm.fixranks
   fixstaff:
     description: Adds the player rank to an admin and restacks their ranks correctly
     usage: /<command> <player>
     permission: APPerm.fixstaff
   listgroups:
       description: Shows a player's current groups
       usage: /<command> <player>
       permission: APPerm.listperms
   apgiveplot:
       description: Gives a plot to a player in the donorPlots world
       usage: /<command> <player>
       permission: APPerm.giveplot
