name: APPerms
main: ap.apperms.apdevteam.Main
version: 1.0.0
authors: [Foxtrot2400, TylerS1066]
depend: [Vault]
commands:
   apgivedonor:
       description: Gives a player a donor rank
       usage: /<command> <player> <rank>
       permission: APPerm.givedonor
   apremovedonor:
       description: Removes a player's donor ranks
       usage: /<command> <player>
       permission: APPerm.removedonor
   apfixdonor:
       description: Fixes the donor permissions for a player by re-stacking their ranks
       usage: /<command> <player>
       permission: APPerm.fixdonor
   aplistgroups:
       description: Shows a player's current groups
       usage: /<command> <player>
       permission: APPerm.listperms
